### ISSUE TITLE
Broken Appspot Link

### ISSUE THREAD

**Issue by iRitwik** [twitter/opensource-website#10]
http://socghop.appspot.com/ gives a 404 not found.

**Comment by necolas** [comment]
This doesn't seem related to this repo. If it is, please be clearer about what we're meant to be looking for. Thanks

**Comment by iRitwik** [comment]
I am sorry. I realize might have posted in the wrong section. Here is the link to the page I was referring to. The link appears on the last header "General Proposal Requirements".

https://github.com/twitter/twitter.github.com/wiki/Google-Summer-of-Code-2013

![gsoctwit](https://f.cloud.github.com/assets/797505/309689/f1818516-9707-11e2-964f-9360e1c3bd06.jpg)

**Comment by necolas** [comment]
cc @caniszczyk

**Comment by caniszczyk** [comment]
Fixed with https://github.com/twitter/twitter.github.com/wiki/Google-Summer-of-Code-2013/71c7e593d336403f9fb2de158b976f921e50d00f
