### ISSUE TITLE
Require CONTRIBUTING.md

### ISSUE THREAD

**Issue by konojunya** [twitter/opensource-website#104]
You should add `CONTRIBUTING.md` because this repository doesn't have `CONTRIBUTING.md` and you have to read the code to get an overview of the repository. For example: https://github.com/twitter/twemoji/blob/master/CONTRIBUTING.md

**Comment by gouravmohanty7070** [comment]
Can I take up the issue?

**Comment by willnorris** [comment]
It looks like there is already a pr in flight for this (#105)
