### ISSUE TITLE
I will add boxes around "heat , light , love " 

### ISSUE THREAD

**Issue by jaiswalpalak** [twitter/opensource-website#107]
![Screenshot (479)](https://user-images.githubusercontent.com/78416508/112750724-de9d4c00-8fe7-11eb-904f-268bc6fde545.png)
I
![Screenshot (480)](https://user-images.githubusercontent.com/78416508/112750852-87e44200-8fe8-11eb-9b7c-cdc8504ea84a.png)
 will add boxes and it will look great then like this

**Comment by willnorris** [comment]
I think we'll leave the design how it is now.  Thanks for the suggestion, though!
