### ISSUE TITLE
Add "dark mode" button in this website!!

### ISSUE THREAD

**Issue by jaiswalpalak** [twitter/opensource-website#108]
I am adding the button named "D" , if we click on that then the dark mode will be activated. Dark mode is here to help with this, making the screen easier to see in low lighting such as in the night or early morning. It can be a lot easier on the eyes, causing less strain and is better in the long run. So can you assign me this because I want to contribute in this.

**Comment by willnorris** [comment]
dark mode added in 76981e0da5d65c6ca04ce6fe74d97473b189942d and subsequent commits.  No button, but rather the site respects the dark mode preference set in the browser.
