### ISSUE TITLE
Twitter Spaces need bug fixing

### ISSUE THREAD

**Issue by Kate028** [twitter/opensource-website#112]
### **Description**
Sometimes unable to hear other people's voices over twitter Spaces.

**Comment by Kate028** [comment]
I think this isn't the right place to report bugs. So closing the issue.

edited: Well I don't know where to mention this issue. Any kinda help will be great.

**Comment by willnorris** [comment]
Leaving feedback through the Twitter app itself will get it routed to the right team.
