### ISSUE TITLE
Eu quero essas reações para o twitter e com filtros na pesquisa.

### ISSUE THREAD

**Issue by ghost** [twitter/opensource-website#113]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Just Do It**
![image](https://user-images.githubusercontent.com/38570195/115031939-bd1cdb00-9e96-11eb-934b-2ac6d98c235b.png)
![image](https://user-images.githubusercontent.com/38570195/115031973-c73ed980-9e96-11eb-8563-dac5ff400d92.png)

**Comment by andypiper** [comment]
It's not clear that this issue relates to the Twitter Open Source web page, and the feature request description is not filled out, so I'm going to close this for now.

**Comment by ghost** [comment]
refer to source code of web app twitter.com.
