### ISSUE TITLE
link not render of chromium when should to be render

### ISSUE THREAD

**Issue by ghost** [twitter/opensource-website#114]
refers to twitter.com

**Is your feature request related to a problem? Please describe.**

When a link is published from the bugs.chromium.org a preview of the link is not generated as when it occurs with other links.

**Describe the solution you'd like**

Generate a preview of the bugs.chromium.org

**Describe alternatives you've considered**

**Additional context**

**an example of a bugs.chromium.org that has no preview generated.**
![image](https://user-images.githubusercontent.com/38570195/115038305-6666cf80-9e9d-11eb-986d-8d28b702254a.png)

**an example link with preview generated.**
![Captura de tela_2021-05-27_10-27-27](https://user-images.githubusercontent.com/38570195/119844619-95c61e80-bed6-11eb-8aef-9d55ce2dd17c.png)

**Comment by willnorris** [comment]
Similar to #113, this doesn't appear to be related to this repo.  If you can provide any more details, that'd be helpful.

**Comment by ghost** [comment]
> Similar to #113, this doesn't appear to be related to this repo. If you can provide any more details, that'd be helpful.

This two issues have diff and require two development.

**Comment by ghost** [comment]
you could have informed me the correct place where I post this feedback.

**Comment by willnorris** [comment]
I'm still not sure what your feedback is.  You didn't fill out the issue template to describe the issue at all.  You provided a screenshot of a Chrome browser displaying a tweet, but I'm not really sure what I'm supposed to be looking at in that screenshot.  Is something not rendering the way you would expect?  I'm happy to point you to the best place to provide the feedback, but as I said above, I need more details to be able to help you.

**Comment by ghost** [comment]
Ready, I filled it out, can you see if you can understand now?

**Comment by willnorris** [comment]
Got it, that's definitely more helpful!  Those link previews are generated from metadata that publisher include on the pages themselves.  Full documentation can be found at https://dev.twitter.com/cards and there is a validator that can help with testing what these previews will look like at https://cards-dev.twitter.com/validator.

In the case of the Chromium bug tracker, Google would need to add the appropriate metadata to those pages.  Fortunately, the bug tracker itself is an open source project called Monorail (https://opensource.google/projects/monorail), so if you're feeling up to it, you might be able to provide them a patch to add support for Twitter Cards.

**Comment by willnorris** [comment]
And actually, here is an existing issue from just a few months ago for adding metadata for page previews: https://bugs.chromium.org/p/monorail/issues/detail?id=8717.  That issue mentions Facebook previews and opengraph tags, but most of those are picked up by Twitter as well.  Again, you could use the Card Validator link above to confirm how it would be rendered.

**Comment by andypiper** [comment]
You can ask questions about Cards on the Twitter Developer Community site [here](https://twittercommunity.com/c/publisher/cards/8).
