### ISSUE TITLE
Readme Dosent say much about the project 

### ISSUE THREAD

**Issue by aryasoni98** [twitter/opensource-website#116]
**Describe the bug**
Readme Dosent Describe The Project Very Well Making it hard to know the total purpose of the project at a glance
Update project readme file

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by willnorris** [comment]
fixed in c3fb27ebe73e713f258cd8dfeafea4c360723ee9
