### ISSUE TITLE
Catch API errors

### ISSUE THREAD

**Issue by jeroen** [twitter/opensource-website#13]
When the `jsonp` github api throws an error, it doesn't use the http status code, but instead the error code ends up in the response body, e.g:

```
jQuery17109736815500073135_1389722497469({
    "meta": {
        "X-RateLimit-Limit": "60",
        "X-RateLimit-Remaining": "0",
        "X-RateLimit-Reset": "1389723035",
        "X-GitHub-Media-Type": "github.beta",
        "status": 403
    },
    "data": {
        "message": "API rate limit exceeded for 198.72.206.137. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
        "documentation_url": "http://developer.github.com/v3/#rate-limiting"
    }
})
```

You should probably notify the user that there was a problem with the API and perhaps display that `data.message` when `meta.status != 200`

**Comment by caniszczyk** [comment]
This is the wrong venue to report this type of issue. API related inquiries go to dev.twitter.com:
https://dev.twitter.com/discussions

**Comment by jeroen** [comment]
It's not about the twitter API, it's about the twitter.github.io front-end not properly fetching the content from the github api.

**Comment by caniszczyk** [comment]
Ah, sorry, wrong assumption!

**Comment by arthurvr** [comment]
This is just an API limitation where you have to live with. We're having the [same issue](https://github.com/h5bp/h5bp.github.io/issues/9) in a similar site.
