### ISSUE TITLE
Twitter Open source project status page doesn't show correct project status labels icons.

### ISSUE THREAD

**Issue by krvaibhaw** [twitter/opensource-website#131]
**Describe the bug**

Twitter Open source project status page doesn't show correct project status labels icons.
Broken links to the status label icons.

**To Reproduce**

1. Go to [opensource-website / content](https://github.com/twitter/opensource-website/tree/main/content)
2. Click on `status.md` page
3. Scroll down to 'Idea' status

**Expected behavior**

Correct label icons corresponding to the project status should be displayed.

**Additional context**

Changing the broken links in the ``status.md`` file should fix the issue.

**Comment by willnorris** [comment]
Thanks for raising the issue.  While GitHub will render markdown pages as you browse the repo as you've described, that's not how the pages are intended to be viewed.  For example, the page you referenced is https://opensource.twitter.dev/status/, which renders as intended.

The problem with the change in #132 is that it messes up local development.  For example, we actually spent a [fair amount of time](https://github.com/twitter/opensource-website/commits/main/static/status) tweaking the color and display of the badges, which we were able to do by running hugo locally and seeing our local changes.  Changing the image references to always use the full URL breaks that ability.

**Comment by krvaibhaw** [comment]
Thanks for the info 😊, I see the full URL will not allow the space for quick tweaking in local deployment. I thought that the status page is not rendering correctly (as in the case of GitHub repo). Haven't known about the color tweaking issues.
