### ISSUE TITLE
There is an error in the number of repos of twitter

### ISSUE THREAD

**Issue by ghost** [twitter/opensource-website#147]
**Describe the bug**
In the image that shows the number of open-source repos of github there is an error, it shows 100 repos and there are only 97.

**To Reproduce**

1. Go to the website
2. Scroll down to "Explore projects"
3. See error

**Expected behavior**
The image should say 97 public repos

**Environment**
Arch linux, Firefox 105.0.3

**Comment by Adi-ty** [comment]
Hey I would like to work on this issue please assign this to me

**Comment by Vrushutup** [comment]
@sebi-vscode2  is this issue resolved ?

**Comment by sebi-vscode2** [comment]
No
