### ISSUE TITLE
need to add image zoom button needed to improve sharpness for users

### ISSUE THREAD

**Issue by FrankFeenix** [twitter/opensource-website#150]

**Comment by FrankFeenix** [comment]
Uploaded photos are sometimes quite blurry which annoys users, so I suggest adding a photo zoom button so they can have a better visual experience

**Comment by andypiper** [comment]
This repository is for the Twitter Open Source website https://opensource.twitter.dev/ - it is not for suggesting features or changes to Twitter.com. Thank you.
