### ISSUE TITLE
Typo on the French UI

### ISSUE THREAD

**Issue by omahs** [twitter/opensource-website#192]
**Describe the bug**
In the field to answer to a post, It says "Postez votrce réponse !" instead of "Postez votre réponse !"

**To Reproduce**
1. Go to Twitter or X on your browser
2. Set your language to French
3. Try to reply to any post
4. Encounter the typo

_______
<img width="592" alt="x" src="https://github.com/twitter/opensource-website/assets/73983677/2590ad20-1217-4f05-af72-30fcd533b90d">

**Comment by Ashu-Jha004** [comment]
Can I give it a shot?

**Comment by imSyntn** [comment]
It's Fixed.

**Comment by omahs** [comment]
This issue has been fixed, thanks!
