### ISSUE TITLE
Add Search bar and Collections type of bookmarks in the Bookmark Section

### ISSUE THREAD

**Issue by MachoMaheen** [twitter/opensource-website#264]
Problem:
I have a lot of Bookmarks in my twitter account.  So finding the required bookmark is so difficult. And also my bookmarks are related to different categories, but  currently the twitter doesn't support the option of adding bookmarks as categorised bookmarks

Solution:
Create a Search Bar Component in the Bookmark Section and also add the option to direct the bookmarks to the user defined collections when clicking the bookmark button.

**Comment by CrazyRacketSmash** [comment]
I can take over this issue and try to reproduce that. Thanks for the suggestion.

**Comment by hvaria** [comment]
Isn't it already implemented https://github.com/twitterdev/bookmarks-search ?

**Comment by CrazyRacketSmash** [comment]
I see...I thought it hadn't because this issue is still open, but thanks for the heads-up.
