### ISSUE TITLE
IE7/IE8 issues

### ISSUE THREAD

**Issue by necolas** [twitter/opensource-website#3]
I'm not sure what your support policy is. There are some issues in IE7 if that matters to you. Screenshot of IE7 below.

![](http://i.imgur.com/eHPog.png)

There more significant ones are:
- There's `NaN` rather than the date being shown against repos in the header. This is also happening in IE8.
- There is no bottom margin to the header because IE7 has this weird bug where it eats bottom margins of floated children under certain circumstances. Some details about the bug in this post - http://nicolasgallagher.com/better-float-containment-in-ie/
- I found that scrolling was _really_ slow.

**Comment by nullpixel** [comment]
Yah this is because twitter is html 5. IE 7+8+9 don't support much html 5. Update your browser ;)

**Comment by ghost** [comment]
Update your browser.

**Comment by andypiper** [comment]
Closing as outdated, IE 7-9 usage is trivially small at this point.
