### ISSUE TITLE
Search for repositories

### ISSUE THREAD

**Issue by erilyth** [twitter/opensource-website#49]
It starts getting quite difficult to search for repositories based on language since the number has exceeded 100 repos. Wouldn't it be better if we add a simple search based on language so people can take a look at languages which they prefer to contribute to.

**Comment by ZolnerBen** [comment]
Ya like php or java that is good with server side search engines. Java script or sql is good for fast processing.

**Comment by AmberSahdev** [comment]
Meanwhile, you can just use ctrl+f.

**Comment by OrkoHunter** [comment]
I have submitted a Pull Request #69 implementing a search box. Please have a look!
