### ISSUE TITLE
Twitter API response error code

### ISSUE THREAD

**Issue by routbiplab** [twitter/opensource-website#70]
GET: https://api.twitter.com/1.1/statuses/home_timeline.json
Auth Type: 1.0
Consumer  key : ####
Consumer secret : ####
Token: ####
Token secret: ####
Signature Method: HMAC-SHA1

Expected Result : Returns a collection of the most recent Tweets and Retweets posted by the authenticating user and the users they follow

Actual Result: {
    "errors": [
        {
            "code": 32,
            "message": "Could not authenticate you."
        }
    ]
}

**Comment by DuncanHills** [comment]
@routbiplab, this repository is about the source for https://twitter.github.io/. It has nothing to do with the Twitter API. For help using the Twitter public API you can visit https://twittercommunity.com/ or https://developer.twitter.com/en/docs.
