### ISSUE TITLE
Add missing favicon

### ISSUE THREAD

**Issue by decause** [twitter/opensource-website#74]
We forgot to add a favicon! :grimacing:

**Comment by Saurabh3333** [comment]
Sir, Where is it missing? I want to contribute. 

Thanks

**Comment by OrkoHunter** [comment]
@decause I used the favicon used in about.twitter.com

Does this look good? Preview - https://orkohunter.github.io/twitter.github.io/

![screen shot 2018-08-31 at 12 12 38 am](https://user-images.githubusercontent.com/8065913/44872242-95ab7c80-acb2-11e8-8619-688eb8d01310.png)

@Saurabh3333 The [favicon file](https://github.com/twitter/twitter.github.io/blob/master/_layouts/default.html#L29) referenced from the HTML was missing. :D

**Comment by Saurabh3333** [comment]
Thank You @OrkoHunter 
I think the issue has been already fixed.

**Comment by ahtee** [comment]
I don't see a change live, was there a PR you wanted to mention @Saurabh3333
