### ISSUE TITLE
Research about TwitterOSS Metrics page

### ISSUE THREAD

**Issue by taiphamhdweb** [twitter/opensource-website#76]
Hi Twitter Team,
I'm reviewing "twitter.github.io" site and I'm interested with Metrics page (https://twitter.github.io/metrics/).
I checked "twitter.github.io" repository but I didn't see source code for "Metrics" page. Is this source code private?
Can I download this source code and integrate to my github.io page?
Can you explain help me some step to develop "Metrics" page?

Thanks you very much!

**Comment by zennyboobee** [comment]
I'm waiting description about this "Metrics" page. Please explain more help me.
Thanks you very much!
