### ISSUE TITLE
(FR) language chooser option for twitter GUI / tweetdeck

### ISSUE THREAD

**Issue by drandreaskrueger** [twitter/opensource-website#84]
perhaps this repo twitter/twitter.github.io would have been a better place to ask this question?

see here: https://github.com/twitter/twitter-text/issues/291

I have actually gone through ALL your repos on https://twitter.github.io/projects.html to find something related, but your language processing team works closed source, I suppose? Please forward to them, thanks. Perhaps tomorrow you meet one of them in the cafeteria by chance ...

**Comment by andypiper** [comment]
Hi there - this is the repository for the Twitter open source web portal - unfortunately we are not able to accept questions about the twitter.com website itself via GitHub.

Closing as invalid.
