### ISSUE TITLE
 chasing popups in grid example makes them stay

### ISSUE THREAD

**Issue by bronsen** [twitter/opensource-website#9]
While idling on http://twitter.github.com/bootstrap/scaffolding.html#gridSystem I noticed a few of the little popups would persist.

By chasing them from bottom to top I could reproduce this. These artifacts seem to be popup's popups.
![ibrokeit](https://f.cloud.github.com/assets/170530/111205/4dcd03f6-6aec-11e2-92b0-6a388dffe847.png)

The attached image shows the result.

**Comment by timtrueman** [comment]
This is the repo for http://twitter.github.com/ …looks like you meant to create an issue for Bootstrap: https://github.com/twitter/bootstrap/issues/new

**Comment by caniszczyk** [comment]
Indeed.

**Comment by bronsen** [comment]
Since I had only noticed the issue on the website I intentionally opened the ticket here. However, I will open the ticket there as per your suggestion.

**Comment by necolas** [comment]
The bootstrap website source code is part of the `gh-pages` branch of the bootstrap repo, so that will be the right place to get this bug fixed. Thanks.
