### ISSUE TITLE
Support for bluetooth multimedia devices in transmissions using Periscope

### ISSUE THREAD

**Issue by ginaldolaranjeiras** [twitter/opensource-website#94]
Samsung airdots and other bluetooth audio and voice devices have malfunctions during live broadcasts.  Support for bluetooth devices required.

**Comment by andypiper** [comment]
Hi there - this is the repository for the Twitter open source web portal - unfortunately we are not able to accept questions about the twitter.com website itself via GitHub.

Closing as invalid.
