### ISSUE TITLE
Like count decrement and sync issue

### ISSUE THREAD

**Issue by kunalashar25** [twitter/opensource-website#96]
**Title:** Like count is not decremented from the post when the user removes the Like

**Steps to Reproduce:**
1. Open any post from the timeline.
2. Like the post; Like count should be incremented by 1
3. Remove the like; like count should be decremented by 1 (Issue)
4. Go back to the timeline and verify Like count displayed for the post.
5. Like the same post from the timeline; Like count should be incremented by 1 (Sync issue due to step 3)
6. Remove the like from timeline; like count should be decremented by 1
7. Go back to the post and verify the Like count displayed for the post. (Sync Issue)

**Expected Result:**
1. Like count should be incremented by 1 when the user likes the post and decremented by 1 when removes the like.
2. Like count displayed on opened post and timeline should be the same.
3. The number of users listed under the Like section should match with the Like count.

**Actual Result:**
1. Like count is not decremented when the user removes like from the post (Issue in Step 3).
2. Like count remains the same when the user removes like from opened post and Likes the same post back from the timeline (sync issue).
3. Like count displayed on the timeline and on the opened post doesn't match when the user removes Like from the timeline (Issue in Step 7).

[likeCount.zip](https://github.com/twitter/twitter.github.io/files/4982268/likeCount.zip)

**Comment by andypiper** [comment]
Hi there - this is the repository for the Twitter open source web portal - unfortunately we are not able to accept questions about the twitter.com website itself via GitHub.

Closing as invalid.
