### ISSUE TITLE
Glitch in Twitter desktop app on Windows 10

### ISSUE THREAD

**Issue by abhishekrawat22** [twitter/opensource-website#97]
When I am scrolling down through my laptop on Twitter App of Windows 10, a glitch is occurring on the top bar where we see Home, Explore etc. written.
The issue is that the content while scrolling, is going over that bar for a second, again and again, resulting sometimes in a complete disappearance of that top bar.

**Comment by andypiper** [comment]
This repo is for Twitter’s Open Source software website; unfortunately it is not a place to report bugs or issues in the Twitter apps. You should talk to @TwitterSupport on Twitter - there’s no formal bug tracker.

**Comment by abhishekrawat22** [comment]
Ok thanks, I was not aware.
